---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - act
  - automake
  - chezmoi
  - cmake
  - curl
  - direnv
  - exercism
  - ffmpeg
  - fzf
  - git-filter-repo
  - git-lfs
  - gitui
  - golang-migrate
  - golangci-lint
  - graphviz
  - hashicorp/tap/terraform
  - icu4c@76
  - jq
  - libressl
  - llvm@19
  - nodenv
  - p7zip
  - pnpm
  - postgresql@14
  - pyenv
  - python-packaging
  - rbenv
  - sqlc
  - streamlink
  - unar
  - yt-dlp
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - libevent
  - nmap
  - openssh
  - ssh-copy-id
  - readline
  - mas
  - openssl
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - alacritty
  - docker
  - slack
  - raycast
  - alt-tab
  - visual-studio-code
  - anki
  - intellij-idea-ce
  - nextcloud
  - obsidian
  - mongodb-realm-studio
  - teamviewer
  - tableplus

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 668429425, name: "Downcast             }
  - { id: 1044549675, name: "Elmedia Video Player }
  - { id: 409183694, name: "Keynote              }
  - { id: 539883307, name: "LINE                 }
  - { id: 441258766, name: "Magnet               }
  - { id: 905953485, name: "NordVPN              }
  - { id: 497799835, name: "Xcode                }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
