---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - act
  - automake
  - chezmoi
  - cmake
  - curl
  - direnv
  - exercism
  - ffmpeg
  - fzf
  - git-filter-repo
  - git-lfs
  - gitui
  - golang-migrate
  - golangci-lint
  - graphviz
  - hashicorp/tap/terraform
  - icu4c@76
  - jq
  - libressl
  - llvm@19
  - nodenv
  - p7zip
  - pnpm
  - postgresql@14
  - pyenv
  - python-packaging
  - rbenv
  - sqlc
  - streamlink
  - unar
  - yt-dlp
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - libevent
  - nmap
  - openssh
  - ssh-copy-id
  - readline
  - mas
  - openssl
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - alacritty
  - docker
  - slack
  - raycast
  - alt-tab
  - visual-studio-code
  - anki
  - intellij-idea-ce
  - nextcloud
  - obsidian
  - mongodb-realm-studio
  - teamviewer
  - tableplus

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 668429425, name: "Downcast             }
  - { id: 1044549675, name: "Elmedia Video Player }
  - { id: 409183694, name: "Keynote              }
  - { id: 539883307, name: "LINE                 }
  - { id: 441258766, name: "Magnet               }
  - { id: 905953485, name: "NordVPN              }
  - { id: 497799835, name: "Xcode                }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages:
  - name: abbrev
    state: present
    version: "~> 0.1.2"
  - name: bootsnap
    state: present
    version: "~> 1.18.4"
  - name: brakeman
    state: present
    version: "~> 7.0.2"
  - name: bundler-audit
    state: present
    version: "~> 0.9.2"
  - name: csv
    state: present
    version: "~> 3.3.2"
  - name: did_you_mean
    state: present
    version: "~> 2.0.0"
  - name: digest
    state: present
    version: "~> 3.2.0"
  - name: english
    state: present
    version: "~> 0.8.0"
  - name: erb
    state: present
    version: "~> 4.0.4"
  - name: error_highlight
    state: present
    version: "~> 0.7.0"
  - name: etc
    state: present
    version: "~> 1.4.5"
  - name: faker
    state: present
    version: "~> 3.5.1"
  - name: fcntl
    state: present
    version: "~> 1.2.0"
  - name: fiddle
    state: present
    version: "~> 1.1.6"
  - name: find
    state: present
    version: "~> 0.2.0"
  - name: getoptlong
    state: present
    version: "~> 0.2.1"
  - name: io-nonblock
    state: present
    version: "~> 0.3.1"
  - name: io-wait
    state: present
    version: "~> 0.3.1"
  - name: kamal
    state: present
    version: "~> 2.5.3"
  - name: matrix
    state: present
    version: "~> 0.4.2"
  - name: mutex_m
    state: present
    version: "~> 0.3.0"
  - name: net-ftp
    state: present
    version: "~> 0.3.8"
  - name: net-http
    state: present
    version: "~> 0.6.0"
  - name: nkf
    state: present
    version: "~> 0.2.0"
  - name: observer
    state: present
    version: "~> 0.1.2"
  - name: open-uri
    state: present
    version: "~> 0.5.0"
  - name: open3
    state: present
    version: "~> 0.2.1"
  - name: optparse
    state: present
    version: "~> 0.6.0"
  - name: pathname
    state: present
    version: "~> 0.4.0"
  - name: prime
    state: present
    version: "~> 0.1.3"
  - name: pstore
    state: present
    version: "~> 0.1.4"
  - name: rails
    state: present
    version: "~> 8.0.2"
  - name: rails
    state: present
    version: "~> 8.0.1"
  - name: rails
    state: present
    version: "~> 7.2.2.1"
  - name: readline
    state: present
    version: "~> 0.0.4"
  - name: repl_type_completor
    state: present
    version: "~> 0.1.9"
  - name: resolv-replace
    state: present
    version: "~> 0.1.1"
  - name: rinda
    state: present
    version: "~> 0.2.0"
  - name: rss
    state: present
    version: "~> 0.3.1"
  - name: ruby-lsp
    state: present
    version: "~> 0.23.24"
  - name: ruby-lsp
    state: present
    version: "~> 0.23.23"
  - name: ruby2_keywords
    state: present
    version: "~> 0.0.5"
  - name: set
    state: present
    version: "~> 1.1.1"
  - name: shellwords
    state: present
    version: "~> 0.2.2"
  - name: solid_cable
    state: present
    version: "~> 3.0.7"
  - name: solid_cache
    state: present
    version: "~> 1.0.7"
  - name: solid_queue
    state: present
    version: "~> 1.1.5"
  - name: solid_queue
    state: present
    version: "~> 1.1.4"
  - name: specific_install
    state: present
    version: "~> 0.3.8"
  - name: strscan
    state: present
    version: "~> 3.1.2"
  - name: syntax_suggest
    state: present
    version: "~> 2.0.2"
  - name: syslog
    state: present
    version: "~> 0.2.0"
  - name: tempfile
    state: present
    version: "~> 0.3.1"
  - name: thruster
    state: present
    version: "~> 0.1.13"
  - name: thruster
    state: present
    version: "~> 0.1.12"
  - name: tmpdir
    state: present
    version: "~> 0.3.1"
  - name: tsort
    state: present
    version: "~> 0.2.0"
  - name: typeprof
    state: present
    version: "~> 0.30.1"
  - name: un
    state: present
    version: "~> 0.3.0"
  - name: uuid7
    state: present
    version: "~> 0.2.0"
  - name: weakref
    state: present
    version: "~> 0.1.3"
  - name: yaml
    state: present
    version: "~> 0.4.0"
  - name: zlib
    state: present
    version: "~> 3.2.1"
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - name: pip
    state: present
    version: "==24.3.1"

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
